### ISSUE TITLE
Get FRs ready for veripeditus-server

### ISSUE THREAD

**Issue by Natureshadow** [Veripeditus/game-verimagica#2]
Please check the game idea against what features Veripeditus has right now.

Then, report any missing features as issues in veripeditus-server.

**Comment by Natureshadow** [comment]
Anything new here?

**Comment by Natureshadow** [comment]
Any progress. @Creeparoo?

**Comment by Creeparoo** [comment]
Everything we have currently planned in Veripeditus or already have implemented is enough for the basic idea of Verimagica.
